#!/bin/bash
# Assemble hackathon demo video from screen recordings and title cards.
#
# Prerequisites:
#   1. Screen record the Hermes Agent session → screen_recording.mp4
#   2. Place it in rhombic/assets/video/
#   3. Title cards already generated by generate_title_cards.py
#
# Usage:
#   cd rhombic
#   bash scripts/assemble_video.sh
#
# Output: assets/video/rhombic_demo_final.mp4

set -e
cd "$(dirname "$0")/../assets/video"

TITLE="title_card.png"
CLOSING="closing_card.png"
SCREEN="screen_recording.mp4"  # You record this
WEAVE="../weave_banner.png"
OUTPUT="rhombic_demo_final.mp4"

# Check prerequisites
if [ ! -f "$SCREEN" ]; then
    echo "ERROR: $SCREEN not found. Record the Hermes session first."
    echo ""
    echo "Recording checklist:"
    echo "  1. SSH to hermes, activate venv, run 'python cli.py'"
    echo "  2. Ask: 'Compare cubic and FCC lattices at scale 5'"
    echo "  3. Ask: 'Run the direction weighting experiment with corpus weights'"
    echo "  4. Ask: 'Run the permutation control test'"
    echo "  5. Ask: 'Explain the full mechanism'"
    echo ""
    echo "Save recording to: assets/video/screen_recording.mp4"
    exit 1
fi

echo "=== Assembling rhombic hackathon demo ==="

# Option A: Simple concat (title + screen + closing)
# 5s title card, screen recording, 5s closing card
ffmpeg -y \
  -loop 1 -t 5 -i "$TITLE" \
  -i "$SCREEN" \
  -loop 1 -t 8 -i "$CLOSING" \
  -filter_complex " \
    [0:v]fps=30,format=yuv420p,fade=in:0:15,fade=out:st=4:d=1[title]; \
    [1:v]fps=30,format=yuv420p,scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,fade=in:0:15,fade=out:st=duration-1:d=1[main]; \
    [2:v]fps=30,format=yuv420p,fade=in:0:15,fade=out:st=7:d=1[close]; \
    [title][main][close]concat=n=3:v=1:a=0[out]" \
  -map "[out]" \
  -c:v h264_nvenc -preset p7 -cq 18 \
  -movflags +faststart \
  "$OUTPUT"

echo ""
echo "=== Done ==="
echo "Output: $(pwd)/$OUTPUT"
SIZE=$(du -h "$OUTPUT" | cut -f1)
DURATION=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$OUTPUT" 2>/dev/null | cut -d. -f1)
echo "Size: $SIZE"
echo "Duration: ${DURATION}s"
echo ""
echo "Twitter limits: 512MB, 2:20. Check before upload."
