# -*- coding: utf-8 -*-
"""Asset-1 per-run rate extract — the auditable basis for the measured rates.

Required by the Director's 2026-08-04 ruling (Part 1): `campaign.log` is
gitignored, so the measured rates (llama 30.56 / qwen 51.72 / blended 41.14
min/run) rested on report alone. This script emits a committed extract:
per-run (idx, family, dur_s) rows plus a per-family summary, generated from
the log + manifest at run time — never hand-copied.

Where the A1 restart produced more than one COMPLETE entry for an index, the
LAST entry is used (the bs4xga4 cohort — the geometry the bank was re-executed
under). The raw log itself stays gitignored.

Outputs (both committed):
  results/asset1-bank/rate_extract.csv   idx,family,dur_s  (480 rows, final cohort)
  results/asset1-bank/RATE_EXTRACT.md    typed per-family summary
"""
import csv
import json
import re
from pathlib import Path

R = Path(__file__).resolve().parent.parent
LOG = R / "results" / "asset1-bank" / "campaign.log"
MAN = R / "results" / "asset1-bank" / "bank_manifest.json"
OUT_CSV = R / "results" / "asset1-bank" / "rate_extract.csv"
OUT_MD = R / "results" / "asset1-bank" / "RATE_EXTRACT.md"

man = json.loads(MAN.read_text(encoding="utf-8"))
fam_of = {r["run_index"]: (r.get("family_short") or r.get("family")) for r in man["runs"]}

ends = re.findall(r"RUN_END idx=(\d+) status=(\w+) rc=(-?\d+) dur=(\d+)s",
                  LOG.read_text(encoding="utf-8", errors="ignore"))
n_total = len(ends)
n_complete = sum(1 for e in ends if e[1] == "COMPLETE")

final = {}          # idx -> dur_s, last COMPLETE wins (A1 restart cohort rule)
multi = 0
for idx, status, rc, dur in ends:
    if status != "COMPLETE":
        continue
    i = int(idx)
    if i in final:
        multi += 1
    final[i] = int(dur)

assert len(final) == len(man["runs"]) == 480, (len(final), len(man["runs"]))

with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["idx", "family", "dur_s"])
    for i in sorted(final):
        w.writerow([i, fam_of[i], final[i]])

fams = {}
for i, d in final.items():
    fams.setdefault(fam_of[i], []).append(d)

lines = [
    "# Asset-1 measured per-run rates (extract of record)",
    "",
    "Generated by `scripts/asset1_rate_extract.py` from `campaign.log` (gitignored)",
    "+ `bank_manifest.json`. Re-run the script to reproduce every figure. Duplicate",
    "COMPLETE entries per index (A1 restart) resolve to the LAST = bs4xga4 cohort.",
    "",
    "```",
    f"RUN_END_LINES        = {n_total}",
    f"RUN_END_COMPLETE     = {n_complete}",
    f"INDICES_FINAL        = {len(final)}",
    f"INDICES_WITH_RESTART = {multi}",
]
allv = sorted(final.values())
for fam in sorted(fams):
    v = sorted(fams[fam])
    mean = sum(v) / len(v)
    lines.append(f"{fam:14s} n = {len(v):3d}   mean = {mean/60:6.2f} min/run   "
                 f"min = {v[0]/60:5.1f}   max = {v[-1]/60:5.1f}")
blend = sum(allv) / len(allv)
lines += [
    f"{'blended':14s} n = {len(allv):3d}   mean = {blend/60:6.2f} min/run",
    "```",
    "",
    "The blended mean is the measured version of the withdrawn '~42 min/run' anchor",
    "(Director Part 3, 2026-07-30); the llama mean is the granularity ladder's cost",
    "basis (Director Ask 4, 2026-08-04).",
]
OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
print("\n".join(lines[6:-5]))
print(f"wrote {OUT_CSV.name} ({len(final)} rows) + {OUT_MD.name}")
