"""T1 bank-design/trainer-config table + dataset-identity table generator.

Emits LaTeX and Markdown twins for the Asset-1 paper, reading every value
from source at emit time (asset1_bank.py constants via AST parse,
bank_manifest.json via json) — no hand-copied numerics (XR-001 discipline).

Values that are code-level facts but not module constants (optimizer class,
schedule form, precision, label convention) are quoted as strings with their
source line references from the fix-sources dossier; they are structural
facts, not numerics.
"""
import ast
import json
import sys
from pathlib import Path

RHOMBIC = Path(r"C:\falco\rhombic")
BANK_PY = RHOMBIC / "scripts" / "asset1_bank.py"
DATA_PY = RHOMBIC / "scripts" / "asset1_datasets.py"
MANIFEST = RHOMBIC / "results" / "asset1-bank" / "bank_manifest.json"
OUT = Path(__file__).parent


def module_constants(path, names):
    """Parse top-level NAME = <literal> assignments via AST (no import/exec)."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    got = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1:
            t, val = node.targets[0], node.value
        elif isinstance(node, ast.AnnAssign) and node.value is not None:
            t, val = node.target, node.value
        else:
            continue
        if isinstance(t, ast.Name) and t.id in names:
            try:
                got[t.id] = ast.literal_eval(val)
            except (ValueError, SyntaxError):
                pass
    missing = set(names) - set(got)
    if missing:
        sys.exit(f"FATAL: constants not found in {path.name}: {sorted(missing)}")
    return got


bank = module_constants(
    BANK_PY,
    [
        "FAMILIES", "TASKS", "N_REPLICATES", "SEED_BASE", "DATA_SEED_BASE",
        "MAX_STEPS", "RANK", "LORA_ALPHA", "N_CHANNELS", "BRIDGE_MODE",
        "TARGET_MODULES", "BATCH_SIZE", "GRAD_ACCUM", "LR", "WEIGHT_DECAY",
        "GRAD_CLIP", "WARMUP_STEPS", "MAX_LEN", "EVAL_INTERVAL",
    ],
)
data = module_constants(DATA_PY, ["VAL_SEED", "VAL_SIZE", "POOL_CAP"])

m = json.loads(MANIFEST.read_text(encoding="utf-8"))
runs = m["runs"]
n_runs = len(runs)
n_complete = sum(1 for r in runs if r["status"] == "COMPLETE")
fams = sorted({r["family"] for r in runs})
tasks = sorted({r["task"] for r in runs})
n_reps = len({r["replicate"] for r in runs})
code_fams = sorted(f["model"] for f in bank["FAMILIES"])

# Cross-checks: manifest vs code constants must agree or we stop.
assert fams == code_fams, (fams, code_fams)
assert tasks == sorted(bank["TASKS"]), (tasks, bank["TASKS"])
assert n_reps == bank["N_REPLICATES"], (n_reps, bank["N_REPLICATES"])
assert n_runs == len(fams) * len(tasks) * n_reps == 480, n_runs
assert n_complete == n_runs, f"manifest not fully COMPLETE: {n_complete}/{n_runs}"
eff_batch = bank["BATCH_SIZE"] * bank["GRAD_ACCUM"]
seqs = bank["MAX_STEPS"] * eff_batch

# Structural facts (strings, not numerics) with source anchors.
OPTIMIZER = r"AdamW (lr, weight decay explicit; \(\beta\), \(\epsilon\) library defaults)"
SCHEDULE = "linear warmup then cosine decay to a 0.1 floor"
PRECISION = "bfloat16 base model; float32 adapter parameters"
LOSS = "LM loss over the full padded sequence (labels = input ids; no prompt/pad masking)"

rows = [
    ("Bank shape", f"{len(fams)} families $\\times$ {len(tasks)} tasks $\\times$ {n_reps} replicates = {n_runs} runs (all COMPLETE)"),
    ("Families", " / ".join(f.split('/')[-1] for f in fams)),
    ("Tasks", ", ".join(bank["TASKS"])),
    ("LoRA rank / alpha / channels / bridge", f"r={bank['RANK']}, $\\alpha$={bank['LORA_ALPHA']}, {bank['N_CHANNELS']} channels, {bank['BRIDGE_MODE']}-initialized bridge"),
    ("Target modules", ", ".join("\\texttt{%s}" % t.replace("_", "\\_") for t in bank["TARGET_MODULES"])),
    ("Optimizer", OPTIMIZER),
    ("Peak LR / weight decay / clip", f"{bank['LR']} / {bank['WEIGHT_DECAY']} / max-norm {bank['GRAD_CLIP']}"),
    ("LR schedule / warmup", f"{SCHEDULE}; {bank['WARMUP_STEPS']} warmup steps"),
    ("Steps / batch geometry", f"{bank['MAX_STEPS']} optimizer steps $\\times$ (batch {bank['BATCH_SIZE']} $\\times$ accum {bank['GRAD_ACCUM']}) = effective {eff_batch}; {seqs:,} sequences"),
    ("Sequence length", f"{bank['MAX_LEN']} tokens"),
    ("Precision", PRECISION),
    ("Loss", LOSS),
    ("Seeds", f"train {bank['SEED_BASE']}+run\\_index; data {bank['DATA_SEED_BASE']}+run\\_index; val split seed {data['VAL_SEED']}"),
    ("Pools / validation", f"pool cap {data['POOL_CAP']:,} per task; fixed {data['VAL_SIZE']}-example val split per task (seed {data['VAL_SEED']}, identical across runs)"),
    ("Eval cadence", f"train+val loss every {bank['EVAL_INTERVAL']} optimizer steps"),
]

tex = ["% AUTO-GENERATED by make_t1.py from asset1_bank.py + asset1_datasets.py +",
       "% bank_manifest.json — regenerate, never hand-edit values.",
       "\\begin{table}[t]", "\\centering", "\\small",
       "\\begin{tabular}{@{}p{0.32\\linewidth}p{0.62\\linewidth}@{}}", "\\toprule",
       "\\textbf{Design element} & \\textbf{Value} \\\\", "\\midrule"]
for k, v in rows:
    tex.append(f"{k} & {v} \\\\")
tex += ["\\bottomrule", "\\end{tabular}",
        "\\caption{Asset-1 bank design and training configuration. Every run",
        "records its full config and library versions in its own",
        "\\texttt{config.json}; the bank manifest pins per-run seeds and status.}",
        "\\label{tab:t1-bank-design}", "\\end{table}"]

md = ["<!-- AUTO-GENERATED by make_t1.py — regenerate, never hand-edit values. -->",
      "| Design element | Value |", "|---|---|"]
for k, v in rows:
    clean = (v.replace("$\\times$", "x").replace("\\texttt{", "`").replace("}", "`")
             .replace("\\(\\beta\\)", "beta").replace("\\(\\epsilon\\)", "eps")
             .replace("\\_", "_"))
    md.append(f"| {k} | {clean} |")

# Dataset-identity table (S3) — IDs/templates are structural facts from
# asset1_datasets.py (dossier item C); pool/val numerics from parsed constants.
DATASETS = [
    ("alpaca", "yahma/alpaca-cleaned", "instruction(+input) $\\to$ response, Alpaca-style \\#\\#\\# template"),
    ("code", "sahil2801/CodeAlpaca-20k", "instruction(+input) $\\to$ response, same template family"),
    ("math", "openai/gsm8k (config main)", "step-by-step solve instruction; question $\\to$ answer"),
    ("xsum", "EdinburghNLP/xsum", "summarize instruction; document (token-budget truncated) $\\to$ summary"),
    ("squad", "rajpurkar/squad (v1.1)", "answer-from-passage instruction; context+question $\\to$ first gold answer"),
    ("agnews", "fancyzhx/ag\\_news", "4-way classify instruction; text $\\to$ class name"),
]
tex2 = ["% AUTO-GENERATED by make_t1.py — dataset identities (dossier item C).",
        "\\begin{table}[t]", "\\centering", "\\small",
        "\\begin{tabular}{@{}llp{0.5\\linewidth}@{}}", "\\toprule",
        "\\textbf{Task} & \\textbf{Source dataset (HF id)} & \\textbf{Formatting} \\\\", "\\midrule"]
for t, src, fmt in DATASETS:
    tex2.append(f"{t} & \\texttt{{{src}}} & {fmt} \\\\")
tex2 += ["\\bottomrule", "\\end{tabular}",
         f"\\caption{{Task sources. All six load the HF \\texttt{{train}} split; a single canonical shuffle (seed {data['VAL_SEED']}) fixes a {data['VAL_SIZE']}-example validation split and a {data['POOL_CAP']:,}-example training pool per task; per-run order is reshuffled by \\texttt{{data\\_seed}}.}}",
         "\\label{tab:t2-datasets}", "\\end{table}"]

(OUT / "T1_table.tex").write_text("\n".join(tex) + "\n", encoding="utf-8")
(OUT / "T1_table.md").write_text("\n".join(md) + "\n", encoding="utf-8")
(OUT / "T2_datasets.tex").write_text("\n".join(tex2) + "\n", encoding="utf-8")
print(f"OK: {n_runs} runs ({n_complete} COMPLETE), {len(fams)}x{len(tasks)}x{n_reps}; eff_batch={eff_batch}; seqs={seqs:,}")
print("wrote T1_table.tex / T1_table.md / T2_datasets.tex")
